Codeinwp/visualizer

classes/Visualizer/Gutenberg/Block.php

This adds a permission callback to Rest request. @contactashish13

Add permission callback

---

classes/Visualizer/Module/Chart.php

Fix Label other is not visible on PIE chart Codeinwp/visualizer#900

---

classes/Visualizer/Gutenberg/Block.php
classes/Visualizer/Module/Chart.php

Close Codeinwp/visualizer-pro#339

Fix security vulnerability

---

js/render-chartjs.js

Fix axis data format issue

---

classes/Visualizer/Module.php
classes/Visualizer/Module/Chart.php
classes/Visualizer/Plugin.php

Chart unique title

---

classes/Visualizer/Module/Admin.php
classes/Visualizer/Module/Chart.php
classes/Visualizer/Module/Frontend.php
classes/Visualizer/Render/Library.php
css/library.css
js/library.js

Compatible with WPML plugin

---

classes/Visualizer/Module.php
classes/Visualizer/Module/Chart.php
classes/Visualizer/Module/Frontend.php
classes/Visualizer/Plugin.php
classes/Visualizer/Render/Layout.php
js/frame.js

Close Codeinwp/visualizer-pro#323

Compatible Woocommerce data

---

js/render-facade.js
js/render-google.js

The problem: after the first chart started the rendering process, the function `displayChartsOnFrontEnd()`  triggered again.
Because the charts were empty (they were in the process of rendering), this code removed the rendering status `$( 'div.viz-facade-loaded:not(.visualizer-lazy):not(.visualizer-cw-error):empty' ).removeClass( 'viz-facade-loaded' );`
And then this `$('div.visualizer-front:not(.visualizer-lazy):not(.viz-facade-loaded)') put it again in the loop since it considered that they never started the rendering process.
Practically, we were re-rendering the charts that were not finished. 
Thus, the infinite loop was crashing the page.
I simplified the logic. Now, after the page loads, the rendering of the chart is triggered once. 
- Check the rendering of the chars; they should …

Fix multiple charts facade and small google fix

---

.distignore

Fixes https://github.com/Codeinwp/visualizer-pro/issues/409. 
This issue was accounted before by ignoring the examples files on `.distignore` . 
However the location of those files changed with the update of the package [here](https://github.com/Codeinwp/visualizer/pull/369/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L26) .
Updating the path with the current path from the package fixes the issue. 
The tests are no longer present in the package itself, that is why I removed the tests from `.distignore`. 
I also noticed some redundant files were present in the `docs` folder and I also added those to be ignored upon building. 
1. Install the pr plugin into a site. 
2. Check that this path https://<your_domain>/wp-content/plugins/visualizer/vendor/phpoffice/phpsp …

fix: ignore phpspreadsheet samples folder

---

classes/Visualizer/Module/Admin.php
js/survey.js

Closes https://github.com/Codeinwp/visualizer-pro/issues/417
Added NPS survey
1. Go to Chart Library or Support page under Visualizer admin menu.
2. After a short period, an NPS survey will pop up on the right corner of the viewport.
With Browser DevTools, you can check if the deps are loaded.

Add NPS survey

---

js/setup-wizard.js
templates/setup-wizard.php

This is related to what we talked on [Slack](https://vertistudio.slack.com/archives/C06410PC59B/p1708083575148569), about the Loading bar behaviour in Visualizer onboarding.
https://github.com/Codeinwp/visualizer/assets/52494172/ff3eb4f6-86ac-498e-b366-584882153511
https://github.com/Codeinwp/visualizer/assets/52494172/97866eed-ab28-4ff1-9a95-a31973736c51
The new way of loading is **faster**, **goes from left to right and disappears when done** (this should allow the user to focus on the continue button and the upsell notice, instead of the loading bar).
___
Closes #1085

Changes speed and position for the loading bar

---

classes/Visualizer/Render/Layout.php
cypress/integration/default/free-upsell.js

Improved the filter conditions so that only one upsell is present for each category and that the upsell is not present when the pro plugin is active.
Added e2e tests for all upsells using the filter.
> [!NOTE]  
> Once this is merged into `development` the e2e tests from the PRO version should also pass.
NO
1. Check that all upsells work as before.
2. Check that the e2e pass.
Closes Codeinwp/visualizer-pro#418.

fix: e2e tests in pro version Codeinwp/visualizer-pro#418

---

.wordpress-org/blueprints/blueprint.json
CONTRIBUTING.md

Blueprint changes
- enhance the landing page link
- stop the auto-redirect via `visualizer-activated`
- hide the normal wizard submenu page via `visualizer_fresh_install`
NO
Enter on this link https://playground.wordpress.net/?plugin=visualizer&blueprint-url=https://raw.githubusercontent.com/Codeinwp/visualizer/fix/blueprint-redirect/.wordpress-org/blueprints/blueprint.json
You should see only three steps. 
Closes https://github.com/Codeinwp/visualizer/issues/1095

Stop auto-redirect in Preview

---

tests/e2e/specs/onboarding.spec.ts

Added e2e test for the Onboarding Wizard
NO
All E2E Tests must pass.
Closes Codeinwp/dev-internals#72.

chore: added onboarding e2e test

---

classes/Visualizer/Render/Library.php
tests/e2e/playwright.config.js
tests/e2e/specs/admin.spec.js

Updated generated shortcode.
Added E2E test.
NO
1. Tests should pass.
Closes Codeinwp/visualizer-pro#462.

fix: remove lazy from shortcode

---

classes/Visualizer/Module.php
classes/Visualizer/Module/Sources.php
tests/e2e/specs/upsell.spec.js

Remove the database source option from the Personal plan.
Change the upsell message when an upgrade to the Developer plan is required.
Added E2E test to check this behavior.
YES
<details open>
<summary>Personal Plan</summary>
</details>
1. E2E tests should pass
2. On a fresh instance activate VIsualizer PRO with a Personal License
3. Check that the Import from database option is not available and asks for an upgrade to the Developer plan.
Closes Codeinwp/visualizer-pro#458.

fix: remove database from personal plan

---

classes/Visualizer/Module/Admin.php
tests/e2e/specs/gutenberg-editor.spec.js

Fixed widget not loading as a result of the recent changes.
Added E2E test.
NO
1. Use a theme that supports Widgets
2. Go to: **Appearance** > **Widgets**
3. Check that the Visualizer block can be added and that it works as expected.
Closes #1156.

fix: widget not loading

---

classes/Visualizer/Module/Admin.php
tests/e2e/specs/gutenberg-editor.spec.js

Fixed widget not working in Customizer context.
NO
1. On a theme that supports Customizer Widgets
2. Try to add a VIsualizer Chart from the Customizer.
3. All tests should pass.
Closes #1156.

fix: widgets inside customizer

---

classes/Visualizer/Module.php
classes/Visualizer/Module/Setup.php
tests/test-import.php

- Use 10 minutes cron instead of hourly
- Small refactor on the schedules update
NO
- Check the Cron and see if its 10 minutes
Closes https://github.com/Codeinwp/visualizer-pro/issues/474

fix: switch to 10 minutes cron

---

classes/Visualizer/Gutenberg/src/Components/Sidebar/MapSettings.js
classes/Visualizer/Render/Sidebar/Type/GoogleCharts/Geo.php

Change the dead link.
> [!NOTE]
> I also updated the one from the block even if we no longer use it.
NO
- Create a Geo Chart
- Check the link on `3-digit` from `Settings > Map Settings > Region`
Closes https://github.com/Codeinwp/visualizer-pro/issues/478

fix: change geo region doc link

---

classes/Visualizer/Module/Setup.php

A small note for schedule importer in the FREE plugin.
YES/NO
Closes https://github.com/Codeinwp/visualizer-pro/issues/474

chore: notes on chart schedule

---

classes/Visualizer/Module/Admin.php
classes/Visualizer/Render/Library.php
classes/Visualizer/Render/Page/Types.php
css/frame.css
css/library.css
index.php

I've updated the upsell links and buttons as per the Google Doc: https://docs.google.com/document/d/1EeYt1wUqzEq12Xcp8C5bN-XMl66a-8B7U3Mmz_sd3Vs/edit?usp=sharing
For more details please check here https://github.com/Codeinwp/visualizer-pro/issues/475
Closes https://github.com/Codeinwp/visualizer-pro/issues/475

Updated current upsell links and buttons

---

.github/workflows/test-php.yml
phpcs.xml
tests/test-ajax.php

I've fixed the PHP outdated error in the PHPUnit GitHub workflow
Issue https://github.com/Codeinwp/visualizer/pull/1171

Fixed PHP outdated version error

---

.distignore
classes/Visualizer/Module.php
classes/Visualizer/Render/Sidebar.php
composer.json
composer.lock

Migrated PhpSpreadsheet to OpenSpout
Yes
1. Create a chart e.g: pie chart
2. Go to the settings tab
3. Click on the frontend action tab
4. Enable Excel action
Closes https://github.com/Codeinwp/visualizer-pro/issues/497

Migrated PhpSpreadsheet to OpenSpout

---

classes/Visualizer/Module/Frontend.php
tests/e2e/specs/gutenberg-editor.spec.js

Fixed charts rendering issue on page load.
Closes https://github.com/Codeinwp/visualizer-pro/issues/493

Fixed chart rendering on page load

---

classes/Visualizer/Module/Frontend.php
js/render-facade.js

Fixed the lazy loading when chart is diable for lazy-load
Closes https://github.com/Codeinwp/visualizer-pro/issues/493#issuecomment-2900266586

Fixed lazy loading when disabled

---

.distignore
.github/workflows/test-php.yml
composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon
tests/php/static-analysis-stubs/symbols.php

- Add PHPStan
- Use Level 6 along with baseline.
NO
- There are no main code changes.

dev: add PHPStan level 6 with baseline
