Codeinwp/visualizer

css/frame.css
The menus from step 2) are now more compact.
=> Modified style for laptop screens

classes/Visualizer/Plugin.php, css/media.css, index.php, package.json
=> fixed auth cache.

classes/Visualizer/Module/Admin.php, languages/visualizer.pot
https://secure.helpscout.net/conversation/368399169/133699/?folderId=1362294
=> resolve conflict with theme "helpguru"

js/render.js
https://github.com/Codeinwp/visualizer/issues/267
=> trigger a custom event when chart is rendered

CHANGELOG.md, classes/Visualizer/Module/Chart.php, classes/Visualizer/Render/Sidebar/Type/Geo.php, readme.md, readme.txt, themeisle-hash.json
https://github.com/Codeinwp/visualizer-pro/issues/120
=> Style gets to default when we edit > Cancel a chart

tests/test-import.php, tests/test-revisions.php
https://github.com/Codeinwp/visualizer/issues/277
=> changed filter_validate to filter_var

js/render.js
https://github.com/Codeinwp/visualizer/issues/283#issuecomment-408799748
=> Table chart: Unable to format using ICU pattern formatters #283

.travis.yml, js/render.js, phpcs.xml
=> Line chart with timeofday column does not show properly when edited

CHANGELOG.md, classes/Visualizer/Render/Page/Data.php, phpcs.xml, readme.md, readme.txt, themeisle-hash.json
https://github.com/Codeinwp/visualizer/issues/298
=> Scheduled charts: add filter to enable users to change schedule of charts #298

classes/Visualizer/Module/Frontend.php
=> Scheduled charts cannot be viewed on the front end once they get updated at their scheduled time #296

CHANGELOG.md, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Sidebar.php, js/frame.js, readme.md, readme.txt, themeisle-hash.json
=> Provide the correct link depending on the chart-type in manual configuration

classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module/Admin.php, classes/Visualizer/Plugin.php, classes/Visualizer/Render/Sidebar/Type/DataTable.php, css/media.css, index.php, package.json
- Bug while displaying new Table chart (register moment.js if not already registered)
- Correct tagging of pro-only charts
=> Release3.1.1

CHANGELOG.md, css/library.css, readme.md, readme.txt, themeisle-hash.json
=> Table chart: chart with all options prevents user from clicking action buttons in library

classes/Visualizer/Module/Admin.php
=> Warning: A non-numeric value encountered

js/render-google.js
=> Date type column does not work with Combo charts

classes/Visualizer/Module/Frontend.php
=> Multiple instances of chart not showing

classes/Visualizer/Module/Frontend.php, js/render-facade.js
#363 
related to https://github.com/Codeinwp/visualizer/issues/350
=> support multiple instances

classes/Visualizer/Gutenberg/Block.php
=> Undefined index: id in \visualizer\classes\Visualizer\Gutenberg\Block.php on line 124

classes/Visualizer/Module/Chart.php, classes/Visualizer/Source.php
https://github.com/Codeinwp/visualizer-pro/issues/130
=> Date picker for date columns

css/frame.css, css/library.css, js/frame.js, js/render-google.js
=> Google charts do not display with jquery 3.3.x

classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module/Sources.php
=> Change Business plan to Developer plan

classes/Visualizer/Render/Sidebar/Type/DataTable.php
=> Not possible to change column settings of the last column in table chart

classes/Visualizer/Source/Csv.php
=> add support for query language to get subset of data

classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Setup.php, classes/Visualizer/Plugin.php, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Sidebar.php, classes/Visualizer/Source/Query.php, js/frame.js
https://github.com/Codeinwp/visualizer-pro/issues/144
=> Import from WP: add ability to pick up live data

classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module.php, classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Frontend.php, classes/Visualizer/Module/Setup.php, classes/Visualizer/Module/Sources.php, classes/Visualizer/Render/Library.php, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Page/Types.php, classes/Visualizer/Render/Sidebar.php, classes/Visualizer/Source.php, classes/Visualizer/Source/Csv.php, classes/Visualizer/Source/Csv/Remote.php, classes/Visualizer/Source/Query/Params.php, index.php, phpcs.xml, tests/test-import.php, tests/test-revisions.php
=> new PHPCS rules for strict comparison

index.php, readme.md, readme.txt
=> remove (Lite) from the plugin name

classes/Visualizer/Module/Frontend.php
=> Async loading of JS fails to load chart sometimes

classes/Visualizer/Module/Chart.php
=> PRO build failure because test cases fail when PRO is not found

.travis.yml
=> Travis builds for PHP below 5.6 fail with latest WP

classes/Visualizer/Source/Query.php
https://github.com/Codeinwp/visualizer-pro/issues/164
=> Only SELECT queries should be allowed

classes/Visualizer/Module/AMP.php
=> Add a path parameter to override default behavior of AMP pages

css/library.css
=> In the library, table thumbnail makes the options hidden/unclickable

js/render-datatables.js
=> Some DataTable options not working

classes/Visualizer/Source/Json.php
=> import from json does not work on some sources

classes/Visualizer/Module/Utility.php
https://github.com/Codeinwp/visualizer-pro/issues/172
=> Combo chart seems to be a regular line chart

samples/candlestick.csv
https://github.com/Codeinwp/visualizer-pro/issues/173
=> Candlestick manual data gives error on default data

classes/Visualizer/Render/Sidebar/Type/DataTable/DataTable.php
=> fatal error

classes/Visualizer/Module/Utility.php, classes/Visualizer/Render/Sidebar.php, classes/Visualizer/Render/Sidebar/ChartJS.php, classes/Visualizer/Render/Sidebar/Type/GoogleCharts/Gauge.php, classes/Visualizer/Render/Sidebar/Type/GoogleCharts/Geo.php, js/render-chartjs.js
=> add user friendliness

classes/Visualizer/Module.php
=> Improvements to CSS Props for DataTable

classes/Visualizer/Source/Json.php
=> compare header names loosely

classes/Visualizer/Render/Sidebar/Type/DataTable/DataTable.php, js/render-datatables.js
=> header row configuration

classes/Visualizer/Module/Chart.php, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Source/Csv.php, classes/Visualizer/Source/Json.php, js/frame.js
=> Better error messages for invalid CSVs/URLs

classes/Visualizer/Render/Sidebar.php
=> Remove strict comparison while rendering select element

classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module.php, classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Sources.php, classes/Visualizer/Render/Layout.php, classes/Visualizer/Render/Library.php, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Page/Update.php, index.php
=> Use filter instead of constant VISUALIZER_PRO

classes/Visualizer/Module/Admin.php, readme.txt
=> Inconsistent chart type listing in library, types screen and readme

classes/Visualizer/Module.php, classes/Visualizer/Module/Setup.php, classes/Visualizer/Render/Library.php, js/library.js, templates/docs.php
=> Test 3.3.0

classes/Visualizer/Module/Utility.php
https://github.com/Codeinwp/visualizer-pro/issues/186
=> Combo chart does not work with combo setting "candlechart"

classes/Visualizer/Module/Utility.php
https://github.com/Codeinwp/visualizer-pro/issues/185
=> Inconsistency when displaying candlechart

classes/Visualizer/Module/Frontend.php, js/render-google.js
https://github.com/Codeinwp/visualizer-pro/issues/188
=> Certain chart types won't display on the post

classes/Visualizer/Render/Page/Data.php, js/frame.js
=> Show chart automatically when user clicks on another menu item

classes/Visualizer/Module.php
=>  customization.js does not load on secondary sites

classes/Visualizer/Plugin.php
=> Change upgrade link

.travis.yml, classes/Visualizer/Render/Sidebar.php, classes/Visualizer/Source.php, readme.md, readme.txt
=> Increase minimum requirement to PHP 5.6

classes/Visualizer/Render/Layout.php
=> Can’t edit chart while importing data from Google Spreadsheet

classes/Visualizer/Module/Chart.php, tests/test-import.php
=> Cloning a chart resets the chart library to Google

classes/Visualizer/Module/Utility.php
=> ChartJS: manual addition of data changes color for existing values

classes/Visualizer/Module/Chart.php
=> clone all post meta

readme.txt
Note: Removed canvas, added table-related tags. Not sure if there's a limit on how many tags are optimal, just added these so we can show up on table-related search.
=> Minor updates, table-related tags

classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Sidebar.php, classes/Visualizer/Render/Sidebar/ChartJS.php, classes/Visualizer/Render/Sidebar/Graph.php, classes/Visualizer/Render/Sidebar/Type/ChartJS/Pie.php, classes/Visualizer/Render/Sidebar/Type/DataTable/DataTable.php, css/frame.css
=> add messages to improve UX

classes/Visualizer/Render/Layout.php, classes/Visualizer/Render/Page/Data.php
#533 
related to the second link in https://secure.helpscout.net/conversation/960428242/202130/
=> escape data before showing

classes/Visualizer/Gutenberg/Block.php
Fixed the issues as described in the helpscout ticket. Link to ticket:  https://secure.helpscout.net/conversation/960428242/202130/
@contactashish13
=> Fix rest route

js/render-google.js
=> Format applied to hAxis does not apply to tooltips

classes/Visualizer/Module/Frontend.php, classes/Visualizer/Render/Sidebar/ChartJS.php, classes/Visualizer/Render/Sidebar/Graph.php, classes/Visualizer/Render/Sidebar/Type/DataTable/DataTable.php
=> add schema support for dataset

classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Setup.php, classes/Visualizer/Plugin.php, classes/Visualizer/Render/Library.php, css/library.css, index.php, js/library.js
=> For every chart show the last updated date and any error that exists

classes/Visualizer/Module.php, classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Sources.php, classes/Visualizer/Render/Page/Data.php
https://github.com/Codeinwp/visualizer-pro/issues/200
=> Add import from wordpress and database to plan 1

classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php
=> PHP Fatal error: Uncaught Error: Cannot unset string offsets

classes/Visualizer/Module/Setup.php
=> Collect more usage statistics

.distignore, .gitignore, .travis.yml, Gruntfile.js, bin/kill-and-create-all.sh, bin/mysql/init-db.sql, bin/run-e2e-tests.sh, bin/wp-init.sh, cypress.env.json.template, cypress.json, cypress/docker-compose.yml, cypress/fixtures/area.csv, cypress/integration/free-lifecycle.js, cypress/integration/free-sources.js, cypress/package.json, cypress/support/commands.js, cypress/support/index.js, docker-compose.travis.yml, package.json
https://github.com/Codeinwp/visualizer-pro/issues/198
=> integrate cypress

readme.md, readme.txt
=> tested upto 5.3

classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Page/Types.php, css/frame.css
https://github.com/Codeinwp/visualizer-pro/issues/217
=> Add undo button for manual editor

classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Setup.php, classes/Visualizer/Plugin.php, classes/Visualizer/Render/Layout.php, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Source/Query.php, classes/Visualizer/Source/Query/Params.php, js/frame.js
https://github.com/Codeinwp/visualizer-pro/issues/203
=> Ability to import from external databases

classes/Visualizer/Module/Chart.php, classes/Visualizer/Render/Layout.php, classes/Visualizer/Render/Page/Data.php, css/frame.css, js/frame.js
https://github.com/Codeinwp/visualizer/issues/481
=> use Show Chart button to trigger submit

CHANGELOG.md, classes/Visualizer/Plugin.php, classes/Visualizer/Render/Page/Data.php, css/media.css, index.php, package.json, readme.md, readme.txt, themeisle-hash.json
=> Test with WP 5.3

cypress/integration/free-lifecycle.js, readme.txt
=> cypress failure

cypress/integration/free-lifecycle.js
=> better handling of chart types screen

cypress/integration/free-lifecycle.js
=> syntax error

.travis.yml, bin/run-e2e-tests.sh, cypress/fixtures/pie.csv, cypress/integration/free-sources.js
=> changes in cypress

.travis.yml, classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module/Sources.php, classes/Visualizer/Render/Sidebar/Type/DataTable/DataTable.php, js/render-datatables.js, js/render-google.js
=> DataTable charts - Infinity Pagination

js/render-facade.js
https://github.com/Codeinwp/visualizer/issues/591
=> Charts in library don't load after F5 Refresh (half the time?)

js/render-facade.js
https://github.com/Codeinwp/visualizer/issues/600
=> fix multiple loading of charts in library

classes/Visualizer/Render/Library.php
=> remove the + button

js/render-facade.js
=> prevent hanging of charts

js/render-datatables.js
https://github.com/Codeinwp/visualizer/issues/503#issuecomment-572558557
=> support for both responsive and non responsive tables

classes/Visualizer/Module/Admin.php, classes/Visualizer/Render/Page/Data.php
https://github.com/Codeinwp/visualizer/issues/525#issuecomment-574117125
=> rectify upsell

cypress.json, cypress/integration/free-sources.js
fix bugs found while testing https://github.com/Codeinwp/visualizer-pro/issues/219
=> update cypress tests

classes/Visualizer/Render/Page/Update.php, classes/Visualizer/Source.php, js/preview.js, js/render-google.js
=> final testing comments

classes/Visualizer/Source/Json.php
https://github.com/Codeinwp/visualizer/issues/481
=> bug with refreshing live data

classes/Visualizer/Module.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Render/Layout.php
https://github.com/Codeinwp/visualizer/issues/214#issuecomment-583402100
=> data changed in one editor to be editable in the other

classes/Visualizer/Module/Chart.php
https://github.com/Codeinwp/visualizer-pro/issues/203
=> chart does not get updated

classes/Visualizer/Module.php, classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Frontend.php, classes/Visualizer/Render/Layout.php, classes/Visualizer/Source.php
=> Allow apostrophes in charts

readme.md, readme.txt
https://github.com/Codeinwp/visualizer/issues/656
=> Added bubble chart to readme documentation

classes/Visualizer/Source/Json.php
=> JSON: Add ability to manipulate data before processing

classes/Visualizer/Module/Setup.php
=> bulk activation of plugin aborts activation of subsequent plugins

classes/Visualizer/Module/Frontend.php
=> If structured data does not show, show the reason as an HTML comment

classes/Visualizer/Render/Layout.php, js/frame.js
https://github.com/Codeinwp/visualizer-pro/issues/254
=> Open headers tab by default if credentials are saved

js/render-chartjs.js
=> ChartJS chart does not follow pixel dimensions

classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Setup.php, tests/test-import.php, tests/test-revisions.php
=> fixes for revison wipe

classes/Visualizer/Render/Layout.php
#524 
https://github.com/Codeinwp/visualizer/issues/524#issuecomment-651231563
=> look for table chart instead of tabular charts

classes/Visualizer/Render/Library.php
=> Show chart ID in the chart library

classes/Visualizer/Module/Frontend.php, classes/Visualizer/Render/Sidebar/Google.php
=> Google charts: Do not load old and new JS

classes/Visualizer/Source/Query.php
https://github.com/Codeinwp/visualizer-pro/issues/257
=> Add support for PHP variables in the DB queries

classes/Visualizer/Module/Frontend.php, js/render-facade.js
=> add "permission_callback" and additional validations

classes/Visualizer/Module/Frontend.php
https://github.com/Codeinwp/visualizer-pro/issues/275
=> Can't edit data of the chart in front-end of the website

classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Setup.php, classes/Visualizer/Plugin.php, classes/Visualizer/Source.php
https://github.com/Codeinwp/visualizer/issues/759
=> Import JSON: Reordering columns only reorders the label not the associated data

classes/Visualizer/Gutenberg/Block.php, classes/Visualizer/Module/Setup.php
https://github.com/Codeinwp/visualizer-pro/issues/283
=> HTML text breaks charts(Table) if user is not logged in to WordPress dashboard

classes/Visualizer/Module/Chart.php
https://github.com/Codeinwp/visualizer-pro/issues/284
=> Option to refresh a chart "Live" is not allowed to be saved with "Import from WordPress"

classes/Visualizer/Module/Setup.php
https://github.com/codeinwp/visualizer-pro/issues/285
=> Periodic data synchronization option does not work on WP Multisite (only Live option works)

classes/Visualizer/Module/Chart.php, classes/Visualizer/Render/Layout.php, js/frame.js
=> Permissions tab disappears after a user modifies a chart's data

js/media.js, js/render-google.js
=> Fix google chart library conflict with other plugins

classes/Visualizer/Render/Sidebar/Google.php
Close Codeinwp/visualizer-pro#258
=> Add support of interval role in chart

classes/Visualizer/Source/Query.php
Close Codeinwp/visualizer-pro#302
=> Fix automatic chart refresh issue when use database source data

classes/Visualizer/Module/Chart.php
=> Fix last column dissapear issue when delete header column

classes/Visualizer/Module/Admin.php
=> Fix google line chart loading issue when create chart first time

js/render-google.js
=> Fix chart rendering issue in accordionJS

js/render-chartjs.js
Close Codeinwp/visualizer-pro#307
=> Fix broken chart issue when change font-size

css/library.css, js/library.js
=> Fix broken chart layout issue when add long title

classes/Visualizer/Module/Frontend.php
=> Fix multiple chart rendering issue

js/render-google.js
=> Fix chart landscape view issue in mobile

classes/Visualizer/Module.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Frontend.php, classes/Visualizer/Source/Csv/Remote.php
Close Codeinwp/visualizer-pro#316
=> Fix render chart issue when creating first time chart

js/render-chartjs.js
=> Add latest chartJS library support in bar chart

js/render-google.js
=> Fix horizontal axis value issue

js/render-google.js
=> Orientation rotate issue in mobile

js/render-facade.js, js/render-google.js
Close Codeinwp/visualizer-pro#324
=> Fix console error when render radar/pie chart

classes/Visualizer/Source/Query.php
Close Codeinwp/visualizer-pro#322
=> Fix compatibility issue with Pirate Parrot plugin

classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Frontend.php, classes/Visualizer/Render/Sidebar.php, css/front.css, js/render-facade.js
Close Codeinwp/visualizer-pro#315
=> Improve script performance

classes/Visualizer/Module/Frontend.php
=> Fix multiple charts lazy rendering issue

classes/Visualizer/Module/Chart.php
=> Upgrade jQuery UI core library CDN

classes/Visualizer/Module/Frontend.php
Close Codeinwp/visualizer-pro#324
=> Fix console error when rendering multiple charts

classes/Visualizer/Module/Frontend.php, js/render-facade.js, js/render-google.js
=> Fix multiple charts loading issue

classes/Visualizer/Module/Admin.php, classes/Visualizer/Render/Library.php, css/library.css, js/library.js
Close Codeinwp/visualizer-pro#314
=> Improve upsell section design

classes/Visualizer/Render/Sidebar/Graph.php
Close Codeinwp/visualizer-pro#331
=> Fix display long haxis text issue

classes/Visualizer/Module/Chart.php
=> Fix PHP 8.0 or above compatibility issue

classes/Visualizer/Module/Frontend.php
=> Separate attributes by white space

classes/Visualizer/Module/Admin.php
=> Fix compatibility issue with UCFW plugin

js/render-facade.js
Close Codeinwp/visualizer-pro#335
=> Fix chart rendering issue with custom accordion

classes/Visualizer/Render/Library.php, js/render-google.js
Close Codeinwp/visualizer-pro#333
=> Fix conflict with translation plugins

classes/Visualizer/Render/Sidebar.php
=> Add description field

classes/Visualizer/Module/Admin.php
Close Codeinwp/visualizer-pro#336
=> Fix pagination issue in chart library

classes/Visualizer/Render/Sidebar/Graph.php
=> Fix update minor grid line field

classes/Visualizer/Module/Frontend.php
=> Add new filter for container attributes

classes/Visualizer/Module.php
=> Compatible with TF Random Number Plugin

classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Frontend.php, classes/Visualizer/Render/Library.php, classes/Visualizer/Render/Page/Data.php, classes/Visualizer/Render/Sidebar.php, css/frame.css, css/library.css, cypress.json, js/preview.js, js/render-facade.js, js/render-google.js
Close Codeinwp/visualizer-pro#51
=> Add data filter support

classes/Visualizer/Render/Library.php, css/library.css
=> Change copy shortcode icon

classes/Visualizer/Module.php
=> Fix temp file creation issue on instawp

classes/Visualizer/Module.php, classes/Visualizer/Module/Admin.php, css/frame.css, js/render-google.js
Close Codeinwp/visualizer-pro#348 Codeinwp/visualizer-pro#349 Codeinwp/visualizer-pro#350
=> Fix filter broken layout

js/render-chartjs.js
Close Codeinwp/visualizer-pro#345
=> Fix chartJs javascript error when rendering multiple charts

classes/Visualizer/Source.php, js/render-datatables.js
=> Fixed table chart decimal number issue

classes/Visualizer/Module.php
=> Fix PHP Warning

classes/Visualizer/Module/Admin.php, classes/Visualizer/Render/Library.php, css/library.css
Close  Codeinwp/visualizer-pro#360
=> Show new features on chart library page

classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php, classes/Visualizer/Module/Frontend.php, cypress/integration/gutenberg-datatable/free-gutenberg-datatable.js, cypress/integration/gutenberg/free-gutenberg.js
=> Fixed PHP error when polylang plugin activated

js/render-google.js
Close Codeinwp/visualizer-pro#363
=> Fixed Geo chart flickering issue

classes/Visualizer/Render/Sidebar/ChartJS.php, js/render-chartjs.js
=> Added disable legend option for chartjs chart

classes/Visualizer/Module/Chart.php, js/preview.js
Close Codeinwp/visualizer-pro#364
=> Fixed cross site scripting vulnerability

cypress.json
=> Changed s3 bucket name

js/render-google.js
=> Fixed the chart refresh problem when importing from CSV

classes/Visualizer/Module/Admin.php, classes/Visualizer/Module/Chart.php
=> Fixed the lock feature bypass vulnerability

classes/Visualizer/Module/Frontend.php
Close Codeinwp/visualizer-pro#365
=> Escaped shortcode attribute before render

classes/Visualizer/Module.php, classes/Visualizer/Module/Admin.php, classes/Visualizer/Render/Library.php, classes/Visualizer/Source/Csv.php
=> Compatible with PHP 8.2

.github/dependabot.yml
Dependabot GH Workflow Added 
NO
N/A
Closes https://github.com/Codeinwp/themeisle/issues/1445.
=> Dependabot GH Workflow Added

classes/Visualizer/Render/Sidebar/Type/ChartJS/Pie.php, js/render-chartjs.js
=> Fixed custom format issue in chartjs

cypress/integration/gutenberg-datatable/free-gutenberg-datatable.js
=> Fixed e2e testcase error

classes/Visualizer/Module.php
Close Codeinwp/visualizer-pro#376
=> Fixed data tables horizontal scrolling issue

classes/Visualizer/Render/Sidebar/Google.php
=> Added legend position default label text

classes/Visualizer/Render/Sidebar/Google.php, classes/Visualizer/Render/Sidebar/Type/GoogleCharts/Geo.php
=> Added tooltip default label text

classes/Visualizer/Module/Wizard.php
=> Fixed Gutenberg block error

classes/Visualizer/Gutenberg/Block.php
=> Fixed table chart rendering issue in Gutenberg block

classes/Visualizer/Module.php
Close Codeinwp/visualizer-pro#380
=> Fixed compatibility issue with WP 5.6

classes/Visualizer/Module/Admin.php, composer.json, composer.lock, index.php
=> Added about page integration

classes/Visualizer/Module.php, classes/Visualizer/Module/Chart.php, index.php
Close Codeinwp/visualizer-pro#396
=> Fixed compatibility issue with WP VIP

js/render-facade.js
Close Codeinwp/visualizer-pro#401
=> Fixed animation issue fusion builder

js/render-google.js
Close Codeinwp/visualizer-pro#392
=> Fixed chart data filter issue

js/render-chartjs.js
Close Codeinwp/visualizer-pro#403
=> Fixed tooltip text rendering issue in chartJS

CONTRIBUTING.md
Add basic information about the plugin's working structure.
Quick Access: https://github.com/Codeinwp/visualizer/blob/chore/docs/CONTRIBUTING.md
Closes: https://github.com/Codeinwp/visualizer-pro/issues/413
=> chore: update docs

.wordpress-org/blueprints/blueprint.json, CONTRIBUTING.md
Removed extra metadata data from the `blueprint.json`.
NO
Closes #1095
=> fix: blueprint schema

composer.lock, tests/e2e/specs/upsell.spec.js
Updated the SDK to the latest version.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2785
=> chore: update SDK

classes/Visualizer/Module.php, classes/Visualizer/Render/Layout.php, css/frame.css, js/frame.js, tests/e2e/specs/chart-sources.spec.js, tests/e2e/specs/upsell.spec.js
- `Manual Data` is now free and moved to the top option.
- `Import data from file` and `import data from URl` are now pro features
> [!NOTE]
> Some E2E tests were moved. See https://github.com/Codeinwp/visualizer-pro/pull/460
YES
https://github.com/Codeinwp/visualizer/assets/17597852/17a635bb-4a06-4f87-a9aa-94a7fdddd334
- With the Free version, check the locked up features
Closes https://github.com/Codeinwp/visualizer-pro/issues/442
=> refactor: update pro feature list

index.php
Update the UTM for sidebar upsell of the submenu created by SDK
NO
- Check the link of `Get Visualizer Pro` from admin submenu
Closes #1126
=> refactor: update sidebar upsell utm

classes/Visualizer/Module/Chart.php, classes/Visualizer/Source/Query.php, tests/test-ajax.php
- Improved filtering and unit tests.
- Added check for the multi-site admin role.
- Added method to strip comments from the query.
- Enforce query starts with SELECT keyword.
- Added unit test for comment strip method.
NO
1. Check the linked issue.
2. All tests should pass.
Closes Codeinwp/visualizer-pro#433.
=> chore: improve restricted query and added test

js/render-chartjs.js
Moved the title settings into the plugins object as per the [ChartJs documentation](https://www.chartjs.org/docs/latest/configuration/title.html).
NO
Create a chart using the ChartJs library and add a title. Check if it is visible when adding the chart to a page.
Closes #1133.
=> fix: improper title settings for ChartJS #1133

classes/Visualizer/Module/Admin.php
Added review message as described in the issue.
YES
https://vertis.d.pr/i/pt1S1e
Check issue details.
Closes https://github.com/Codeinwp/visualizer-pro/issues/453.
=> chore: add review notice

classes/Visualizer/Module/Chart.php, tests/test-ajax.php
Restrict access to save SQL query action.
Introduced check for the PRO filter.
NO
1. Check the linked issue for testing and replication instructions.
Closes Codeinwp/visualizer-pro#472.
=> fix: sql for subscriber

.github/workflows/deploy-wporg.yml, Gruntfile.js, readme.md
Updated the job for the deployment to update the store via an action.
Updated the Grunt to correctly generate the `readme.md` from the `readme.txt`.
Manually corrected the changelog inside the store:  [Changelog](https://store.themeisle.com/?edd_action=view_changelog&name=Visualizer%3A%20Charts%20and%20Graphs%20Lite)
NO
1. After release check that the changelog is properly updated on WordPress.org and on the Store.
Closes Codeinwp/visualizer-pro#469.
=> fix: update changelog and workflow

.github/workflows/test-e2e.yml, .github/workflows/test-php.yml, classes/Visualizer/Source.php, classes/Visualizer/Source/Csv.php
Fixed vulnerability issue with the `Import Data From File`.
Yes
Closes https://github.com/Codeinwp/visualizer-pro/issues/503
=> Fixed data escaping issue with import file

js/simple-editor.js
I've excluded duplicate inputs when submitting the simple editor form.
Closes https://github.com/Codeinwp/visualizer/issues/1174
=> Fixed extra column issue with simple editor

classes/Visualizer/Source.php, classes/Visualizer/Source/Csv.php
Fixed special characters rendering issue
Yes
Closes https://github.com/Codeinwp/visualizer/issues/1210
=> Fixed special characters rendering issue
